name: Publish Docker Image to Docker Hub

on: push
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUN }}
          password: ${{ secrets.DOCKERPW }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERUN }}/team1agile

      - name: Docker Push
        run: docker push ${{ secrets.DOCKERUN }}/team1agile
